config/routes.rb
Fidelity::Application.routes.draw do
  get "home/survey_results"

  get "home/survey"

  resources :answers

  resources :questions

  resources :users

  resources :product_attributes

  resources :products

  resources :categories

  get "home/index"
  
  post "home/survey"
  
  post "home/survey_results"

  root :to => 'home#index'

end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base
  belongs_to :product
end

app/controllers/product_attributes_controller.rb
class ProductAttributesController < ApplicationController
  # GET /product_attributes
  # GET /product_attributes.json
  def index
    @product_attributes = ProductAttribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_attributes }
    end
  end

  # GET /product_attributes/1
  # GET /product_attributes/1.json
  def show
    @product_attribute = ProductAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_attribute }
    end
  end

  # GET /product_attributes/new
  # GET /product_attributes/new.json
  def new
    @product_attribute = ProductAttribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_attribute }
    end
  end

  # GET /product_attributes/1/edit
  def edit
    @product_attribute = ProductAttribute.find(params[:id])
  end

  # POST /product_attributes
  # POST /product_attributes.json
  def create
    @product_attribute = ProductAttribute.new(params[:product_attribute])

    respond_to do |format|
      if @product_attribute.save
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully created.' }
        format.json { render json: @product_attribute, status: :created, location: @product_attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_attributes/1
  # PUT /product_attributes/1.json
  def update
    @product_attribute = ProductAttribute.find(params[:id])

    respond_to do |format|
      if @product_attribute.update_attributes(params[:product_attribute])
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_attributes/1
  # DELETE /product_attributes/1.json
  def destroy
    @product_attribute = ProductAttribute.find(params[:id])
    @product_attribute.destroy

    respond_to do |format|
      format.html { redirect_to product_attributes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/product_attributes_helper.rb
module ProductAttributesHelper
end

app/views/product_attributes/_form.html.slim
= form_for @product_attribute do |f|
  - if @product_attribute.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product_attribute.errors.count, "error")} prohibited this product_attribute from being saved:"
      ul
        - @product_attribute.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :attribute
    = f.text_field :attribute
  .field
    = f.label :product_id
    = f.number_field :product_id
  .actions = f.submit 'Save'

app/views/product_attributes/edit.html.slim
h1 Editing product_attribute

== render 'form'

= link_to 'Show', @product_attribute
'|
= link_to 'Back', product_attributes_path

app/views/product_attributes/index.html.slim
h1 Listing product_attributes

table
  tr
    th Attribute
    th Product
    th
    th
    th

  - @product_attributes.each do |product_attribute|
    tr
      td = product_attribute.attribute
      td = product_attribute.product_id
      td = link_to 'Show', product_attribute
      td = link_to 'Edit', edit_product_attribute_path(product_attribute)
      td = link_to 'Destroy', product_attribute, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Product attribute', new_product_attribute_path

app/views/product_attributes/new.html.slim
h1 New product_attribute

== render 'form'

= link_to 'Back', product_attributes_path

app/views/product_attributes/show.html.slim
p#notice = notice

p
  strong Attribute:
  = @product_attribute.attribute
p
  strong Product:
  = @product_attribute.product_id

= link_to 'Edit', edit_product_attribute_path(@product_attribute)
'|
= link_to 'Back', product_attributes_path